title: Project

fields:
  blocks:
    type: blocks # For more info: https://getkirby.com/docs/reference/panel/fields/blocks
    fieldsets:
      # overrides to default blocks found in /site/blueprints/blocks
      - heading
      - text
      - image
      - gallery
      - video
      - info
      slider:
        icon: layers
        fields:
          images:
            type: files
            multiple: true
            layout: cards
            size: tiny
            uploads:
              template: blocks/image
            image:
              ratio: 1/1
