title: Project

fields:
  mybuilder:
    label: Page Builder
    type: blocks # For more info: https://getkirby.com/docs/reference/panel/fields/blocks
    fieldsets:
      - heading
      - text
      - image
      - gallery
      - video
      info:
        icon: question
        fields:
          date:
            type: date
            display: D MMMM YYYY
            width: 1/2
          client:
            type: text
            width: 1/2
          link:
            type: url
            width: 1/2
          role:
            type: text
            width: 1/2
          tags:
            type: tags
            options: query
            query: page.index.pluck("tags", ",", true)
      links:
        icon: attachment
        fields:
          links:
            type: structure
            fields:
              title:
                type: text
              target:
                type: link
                label: Link
                options:
                  - url
                  - tel
                  - email
                settings: false
      # slider:
      #   icon: layers
      #   fields:
      #     images:
      #       type: files
      #       multiple: true
      #       layout: cards
      #       size: tiny
      #       uploads:
      #         template: blocks/image
      #       image:
      #         ratio: 1/1
    